### ISSUE TITLE
re-organize rules to improve flow

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/collaborative-lesson-development#2]
I'd like to suggest a reorganization to improve the flow. Rather than use my words, I'll use a revamped figure to illustrate one potential re-ordering. The number by the text corresponds to the current order so that you can see what I think could be moved up or down in the order.

![2017-05-17-rules-03](https://user-images.githubusercontent.com/7544197/26908877-75f383c2-4bcb-11e7-8190-c26a85d96276.png)

**Comment by gvwilson** [comment]
Thanks for this Rayna - it's a big help.  So just to check, your proposed order is:

1. Clarify audience
2. Build community around lessons
3. Teach how to develop lessons
4. Build modular lessons
5. Encourage contributors
6. Assess and evaluate feedback
7. Remember that you can't please everyone
8. Reduce/re-use/recycle
9. Point to alternate resources
10. Publish periodically with acknowledgments

If so, I partially agree, but I think that:

* We should end with "you can't please everybody"
* We should put "publish periodically" immediately after "encourage contributors", since PP is an important special case of EC
* We should put "teach how to develop lessons" after "build modular lessons", because BML motivates THDL
* We should combine "reduce/re-use/recycle" and "point to alternate resources" (which means coming up with a new tenth point)

This would give us:

1. Clarify audience (CA)
2. Build community around lessons (BC)
3. Build modular lessons (BML)
4. Teach lesson development (TLD)
5. Encourage contributors (EC)
6. Publish periodically (PP)
7. Assess and evaluate feedback (AEF)
8. Reduce/re-use/recycle/point to alternate resources (RRR)
9. Remember that you can't please everyone (CPE)

plus one new point.

Thoughts?

**Comment by ianmilligan1** [comment]
I'm happy with this reordering, and I think it works really well. I will start thinking on a new tenth point too... nothing is immediately coming to me.

**Comment by raynamharris** [comment]
Thanks @gvwilson. I approve of your order. For now, I suggest we keep 'point to alternate resources' to keep the 10 reals and send it out for feedback.
