### ISSUE TITLE
publication charges

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/collaborative-lesson-development#39]

**Comment by ianmilligan1** [comment]
Hard for me to provide an exact figure as I'm in a humanities field without a culture of publication charges, but I should be able to pay my share (tho anything above 500 CAD would require a bit of work).

**Comment by gdevenyi** [comment]
I can kick in whatever needs be from my funder. (no limit within reason i.e. not everything :)

**Comment by DamienIrving** [comment]
Might be a good time for a summary:

Either via email or this thread, myself, @ianmilligan1, @gdevenyi, @k8hertweck and @raynamharris have all said that they can contribute basically whatever is required. The only person we are waiting to hear from is @twitwi.

That means the contribution will either be US$2250 / 5 = US$450 each or US$2250 / 6 = US$375 each.

If PLOS Computational Biology can't handle multiple invoices, @k8hertweck said she can look into managing the payment components from her university. (Otherwise @gvwilson said he can manage the money.)

**Comment by gvwilson** [comment]
Thanks all - I'll know Wednesday what my contribution can be.

**Comment by jduckles** [comment]
If it would be helpful, I think we could have SWC act as the payer for the pub fees. If you each pledge to donate your agreed upon amounts to SWC via [FlipCause](https://software-carpentry.org/join/donate/). Then I'll try to make the case to the SC that this is a worthwhile thing for us to enable.

**Comment by ianmilligan1** [comment]
I can't claim donations, unfortunately, but publication fees are an eligible expense. It's a worthy cause, but I'm currently on parental leave (and my partner is just coming off their own non-topped up parental leave) and am maxed out on other charitable donations, so all things being equal I would prefer being invoiced directly by PLOS or SWC. Hate to be a stick in the mud.

**Comment by gvwilson** [comment]
Confirming that I can pay my share - @twitwi, can you please let us know?

**Comment by raynamharris** [comment]
Thanks for the math @DamienIrving. I had also come up with the $375 number and can definitely pay that. Let me know if the total is any different, but a subtle difference should be fine.

**Comment by raynamharris** [comment]
is this okay to close?
