### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by andreww** [swcarpentry/collaborative-lesson-development#4]
Greg asked for feedback on this via the Software Carpentry discussion email list. Overall, I think this looks like a useful summary of how to build lessons collaboratively. It's also useful for me to see this now as I think we'll be discussing exactly these issues in a mentoring group in a month or so.

- [X] *References added.* I think it would be useful to have a fair number of additional references - I've mentioned some of these below but pretty much every second could benefit from additional links to the literature.
- [X] *Added.* I think it would be worth being more specific about the _learner profiles_ at the end of rule 1 (clarify your audience). It may be useful to point to the software carpentry [learner profiles](https://software-carpentry.org/audience/) as an example, or to add a reference or two to wherever the idea is best or first described.
- [X] *Added.* It may also be useful to define what "done" could look like early in the process of developing a lesson or lessons. This could fit into rule 1 and would help focus lesson developers in a similar way to the learner profiles.
- [X] *We don't actually do this, so it would be hard for us to recommend it.* I wonder if it is worth mentioning the utility of recording the decisions that are made where developing a lesson in some place that can be referred to by future developers. I'm not convinced that this is something that gets done very well in Software Carpentry's lesson development but the decisions that lead to Y being taught before X, and that Z is not included in the lesson is important. Future lesson developers could benefit from knowing why these choices were made, and what the evidence for the choice was. (Maybe an earlier version taught X and Y in the logical order, but assessment and feedback indicated that this didn't work very well. Knowing this would be useful if the order was being reexamined.) I suppose this could fit in Rule 2, 4, 5 or 7.
- [X] *Filed as #22.* While the statement at the end of the first paragraph of Rule 4 ("Unfortunately, since most college and university faculty have little or no training in education, this knowledge and expertise is rarely transferred into classroom practice.") is certainly true, it would strengthen the argument if you could point to some data to back this up.
- [X] *I think this is more detail than we can get into in a "10 Rules" paper.* The issue of understanding the frame of reference of learners described at the end of Rule 7 could also indicate other issues around but not directly related to the lessons being developed (e.g. a lack of other lessons, a lack of opportunity for learners to attend more appropriate workshops, or failure to communicate the objectives or prerequisite material).
- [X] *See #84.* I wonder if it is worth mentioning that it could be worth separating issues highlighted by large scale surveys into those that can be addressed by directly changing the collaboratively developed lesson, and those that are better tacked elsewhere (e.g. by the host organization, or by creating a new lesson to supplement the existing one). This could act as a link between Rule 7 and 8, and links to Rule 10.
- [x] Finally, I spotted an extra closing double quote after 'beginner' on line 58.

**Comment by ntmoore** [comment]
Here's a reference for faculty not having background in education.  In Physics, there is a yearly "New Faculty Workshop" of about a week, sponsored by the American Association of Physics Teachers (AAPT).  One of the the primary purposes of the workshop is to provide a short course for new faculty on the results of Science Education Research (because faculty have little to know knowledge of Education Research when they land that first job...)

Link: http://www.aapt.org/Conferences/newfaculty/nfw.cfm

From the site, purpose of the workshop is:

<quote>
Since 1996, the American Association of Physics Teachers has sponsored workshops designed to help new faculty at research and four-year institutions understand how to become more effective educators and support their quest to gain tenure.

Because of the pressure to establish their credentials in research or other scholarly activities, new faculty may be tempted to postpone or ignore the development of teaching proficiency. They may receive direct or subtle messages suggesting that only a focus on research will result in career advancement, and there is often a lack of mentors or role models who demonstrate dedication and enthusiasm for teaching.

Similar signals are transmitted to graduate students who may be in training for academic careers. Moreover, because the research universities include many of our large public institutions, a large number of undergraduates may suffer as a result of inadequate preparation of new faculty for teaching.

Data suggest that this inadequate attention to teaching, especially in introductory science and math courses, is responsible for driving students away from undergraduate majors in science, mathematics and engineering.
</quote>

**Comment by gvwilson** [comment]
Thanks for the link @ntmoore - I think what @andreww was after was some survey data to show that most faculty don't currently have such training. (That's implied by the workshop's existence, but I couldn't see anything on that site showing how many people do or don't already have training.)
