### ISSUE TITLE
Figure 1

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/collaborative-lesson-development#42]
In Figure 1. The images supporting Tip #7 are not very clear to interpret. I would think of something else here. Perhaps an old-style scale instead of 'great' and 'terrible'? Or something similar.

**Comment by raynamharris** [comment]
My original goal with this illustration was to indicate two things: 
1. that red and green stick notes provide immediate positive and negative feedback 
2. that feedback should be collected at some point in the near future

Since we are referring to timescales, I don't think that using an image of a scale would work, but I could use maybe something like a sand clock. 

Are there any other suggestions for improving tip #7: evaluate lessons at several timescales?
